language: php

php:
  - '7.1'

cache:
  directories:
    - ./vendor

install:
  - composer install
  - npm install

script:
  - vendor/bin/phpunit
  - npm test
  - vendor/bin/psalm
  - vendor/bin/phpcs --standard=PSR2 src/ tests/
