language: php

php:
  - '5.6'

cache:
  directories:
    - ./vendor

install:
  - composer install

script:
  - vendor/bin/phpunit
  - vendor/bin/psalm
  - vendor/bin/phpcs --standard=PSR2 src/ tests/
