openapi: 3.0.0
info:
  title: 'Mill unit test API, Showtimes'
  version: 1.1.2
  contact:
    name: 'Get help!'
    email: support@example.com
    url: 'https://developer.example.com/help'
tags:
  -
    name: Theaters
servers:
  -
    url: 'https://api.example.com'
    description: Production
  -
    url: 'https://api.example.local'
    description: Development
paths:
  /theaters:
    get:
      summary: 'Get movie theaters.'
      description: 'Returns all movie theatres for a specific location.'
      operationId: getTheaters
      tags:
        - Theaters
      parameters:
        -
          description: 'Location you want theaters in.'
          in: query
          name: location
          required: true
          schema:
            type: string
      responses:
        200:
          description: 'Standard request.'
          content:
            application/mill.example.theater+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/theater'
        400:
          description: 'If the location is invalid.'
          content:
            application/mill.example.theater+json:
              schema:
                $ref: '#/components/schemas/error'
      x-mill-path-template: /theaters
    post:
      summary: 'Create a movie theater.'
      description: 'Create a new movie theater.'
      operationId: createTheater
      tags:
        - Theaters
      requestBody:
        required: true
        content:
          application/mill.example.theater+json:
            schema:
              type: object
              properties:
                address:
                  description: 'Theater address'
                  example: '2548 Central Park Ave, Yonkers, NY 10710'
                  type: string
                name:
                  description: 'Name of the theater.'
                  example: 'Alamo Drafthouse Cinema - Yonkers'
                  type: string
                phone_number:
                  description: 'Theater phone number'
                  example: '(914) 226-3082'
                  type: string
              required:
                - address
                - name
                - phone_number
      responses:
        200:
          description: 'Standard request.'
          content:
            application/mill.example.theater+json:
              schema:
                $ref: '#/components/schemas/theater'
        400:
          description: 'If there is a problem with the request.'
          content:
            application/mill.example.theater+json:
              schema:
                $ref: '#/components/schemas/error'
      security:
        -
          oauth2:
            - create
      x-mill-path-template: /theaters
  '/theaters/{id}':
    get:
      summary: 'Get a single movie theater.'
      description: 'Return information on a specific movie theater.'
      operationId: getTheater
      tags:
        - Theaters
      parameters:
        -
          description: 'Theater ID'
          in: path
          name: id
          required: true
          schema:
            type: number
            example: '1234'
      responses:
        200:
          description: 'Standard request.'
          content:
            application/mill.example.theater+json:
              schema:
                $ref: '#/components/schemas/theater'
        304:
          description: 'If no content has been modified since the supplied Last-Modified header.'
        404:
          description: 'If the movie theater could not be found.'
          content:
            application/mill.example.theater+json:
              schema:
                $ref: '#/components/schemas/error'
      x-mill-path-template: /theaters/+id
    patch:
      summary: 'Update a movie theater.'
      description: 'Update a movie theaters'' data.'
      operationId: updateTheater
      tags:
        - Theaters
      parameters:
        -
          description: 'Theater ID'
          in: path
          name: id
          required: true
          schema:
            type: number
            example: '1234'
      requestBody:
        required: true
        content:
          application/mill.example.theater+json:
            schema:
              type: object
              properties:
                address:
                  description: 'Theater address'
                  example: '2548 Central Park Ave, Yonkers, NY 10710'
                  type: string
                name:
                  description: 'Name of the theater.'
                  example: 'Alamo Drafthouse Cinema - Yonkers'
                  type: string
                phone_number:
                  description: 'Theater phone number'
                  example: '(914) 226-3082'
                  type: string
              required:
                - address
                - name
                - phone_number
      responses:
        200:
          description: 'Standard request.'
          content:
            application/mill.example.theater+json:
              schema:
                $ref: '#/components/schemas/theater'
        400:
          description: 'If there is a problem with the request.'
          content:
            application/mill.example.theater+json:
              schema:
                $ref: '#/components/schemas/error'
        404:
          description: 'If the movie movie could not be found.'
          content:
            application/mill.example.theater+json:
              schema:
                $ref: '#/components/schemas/error'
      security:
        -
          oauth2:
            - create
      x-mill-path-template: /theaters/+id
    delete:
      summary: 'Delete a movie theater.'
      description: 'Delete a movie theater.'
      operationId: deleteTheater
      tags:
        - Theaters
      parameters:
        -
          description: 'Theater ID'
          in: path
          name: id
          required: true
          schema:
            type: number
            example: '1234'
      responses:
        204:
          description: 'Standard request.'
        404:
          description: 'If the movie theater could not be found.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      security:
        -
          oauth2:
            - delete
      x-mill-path-template: /theaters/+id
      x-mill-visibility-private: true
components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: bearer
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /oauth/authorize
          tokenUrl: /oauth/access_token
          scopes:
            create: Create
            delete: Delete
            edit: Edit
            public: Public
        clientCredentials:
          tokenUrl: /oauth/authorize/client
          scopes:
            create: Create
            delete: Delete
            edit: Edit
            public: Public
  schemas:
    error:
      properties:
        error:
          description: 'User-friendly error message'
          type: string
    movie:
      properties:
        cast:
          description: 'Cast. This data requires a bearer token with the `public` scope.'
          items:
            $ref: '#/components/schemas/person'
          type: array
        content_rating:
          description: 'MPAA rating'
          enum:
            - G
            - NC-17
            - NR
            - PG
            - PG-13
            - R
            - UR
            - X
          example: G
          type: string
        description:
          description: Description
          type: string
        director:
          allOf:
            -
              $ref: '#/components/schemas/person'
          description: 'Director. This data requires a bearer token with the `public` scope.'
        external_urls:
          description: 'External URLs. This data requires a bearer token with the `public` scope.'
          items:
            type: object
            properties:
              imdb:
                description: 'IMDB URL. This data requires a bearer token with the `public` scope.'
                type: string
              tickets:
                description: 'Tickets URL. This data requires a bearer token with the `public` scope.'
                type: string
                x-mill-vendor-tags:
                  - 'tag:BUY_TICKETS'
              trailer:
                description: 'Trailer URL. This data requires a bearer token with the `public` scope.'
                type: string
          type: array
        genres:
          description: Genres
          items:
            type: string
          type: array
        id:
          description: 'Unique ID'
          type: number
        kid_friendly:
          description: 'Kid friendly?'
          example: 'false'
          type: boolean
        name:
          description: Name
          type: string
        purchase:
          properties:
            url:
              description: 'URL to purchase the film.'
              type: string
          type: object
        rotten_tomatoes_score:
          description: 'Rotten Tomatoes score'
          type: number
        runtime:
          description: Runtime
          type: string
        showtimes:
          description: 'Non-theater specific showtimes'
          items:
            type: string
          type: array
        theaters:
          description: 'Theaters the movie is currently showing in'
          items:
            $ref: '#/components/schemas/theater'
          type: array
        uri:
          description: 'Movie URI'
          type: string
    person:
      properties:
        id:
          description: 'Unique ID'
          type: number
        imdb:
          description: 'IMDB URL'
          type: string
        name:
          description: Name
          type: string
        uri:
          description: 'Person URI'
          type: string
    theater:
      properties:
        address:
          description: Address
          type: string
        id:
          description: 'Unique ID'
          type: number
        movies:
          description: 'Movies currently playing'
          items:
            $ref: '#/components/schemas/movie'
          type: array
        name:
          description: Name
          type: string
        phone_number:
          description: 'Phone number'
          type: string
        showtimes:
          description: 'Non-movie specific showtimes'
          items:
            type: string
          type: array
        uri:
          description: 'Theater URI'
          type: string
security:
  -
    oauth2:
      - create
      - delete
      - edit
      - public
